---
title: "Chapter2 R basics"
output:
  html_document:
    df_print: paged
---

# Chapter 2 _ R basics

## 2.8 Exercise
1.
```{r}
temp <- c(35, 88, 42, 84, 81, 30)
temp
```
2.
```{r}
city <- c("Beijing", " Lagos", "Paris", "Rid de Janeiro", "San Juan", "Toronto")
city
```
3.
```{r}
names(temp) <- city
temp
```
4.
```{r}
city[1:3]
```
5.
```{r}
temp[c(3, 5)]
```
6.
```{r}
seq(12, 73, 1)
```
7.
```{r}
seq(1, 100, 2)
```
8.
```{r}
length(seq(6, 55, by= 4/07))
```
9.
```{r}
a <- seq(1, 10, 0.5)
class(a)
```
10.
```{r}
a <- seq(1, 10)
class(a)
```
11.
```{r}
class(a <- 1L)
```
12.
```{r}
x <- c("1", "3", "5")
as.integer(x)
```

## 2.9 Sorting

###2.9.1 sort

```{r}
sort(murders$total)
```
### 2.9.2 order

```{r}
x <- c(31, 4, 15, 92, 65)
sort(x)
```
```{r}
index <- order(x)
x[index]
```


```{r}
murders$state[1:6]
murders$abb[1:6]
```
```{r}
index <- order(murders$total)
murders$abb[index]
```

### 2.9.3 max and which.max
```{r}
max(murders$total)
```
```{r}
i_max <- which.max(murders$total)
murders$state[i_max]
murders$state[5]
```
```{r}
x <- c(31, 4, 15, 92, 65)
rank(x)
```

### 2.9.5
```{r}
x <- c(1, 2, 3)
y <- c(seq(10, 70, 10))
x+y
```
## 2.10 Exercises

```{r}
library(dslabs)
data("murders")
str(murders)
```

1. 

```{r}
pop <- murders$population
pop <- sort(pop)
pop[3]
```
2.
```{r}
order(murders$population)
```
3.
```{r}
which.min(murders$population)
```
4.
```{r}
murders$state[51]
murders$state[which.min(murders$population)]
```
5.
```{r}
rank <- rank(murders$population)
state <- murders$state
ind
my_df <- data.frame(name = state, rank = rank)
```

6.
```{r}
ind <- order(murders$population)
state[ind]
my_df <- data.frame(states= state[ind], rank = rank[ind])
```

7.
```{r}
data("na_example")
str(na_example)
```
```{r}
mean(na_example)
ind <- is.na(na_example)
sort(ind, decreasing = TRUE)
sum(ind)
```

8.
```{r}
s <- sort(ind, decreasing = TRUE)
sort(ind, decreasing = TRUE)
c <- c(1,1,1,1,1,2,2,2,2,2)
mean(na_example[])
mean(c[6:10])
mean(na_example[!ind])
ind <- order(ind, decreasing = TRUE)
a <- na_example[ind]
mean(a[146:1000])
```
```{r}
na_example
is.na(na_example)
mean(na_example[!is.na(na_example)])

```

## 2.11 Vector arithmetics

```{r}
murders[5]
```

### 2.11.1 Rescalinga vector

```{r}
inches <- c(69, 62, 66, 70, 70, 73, 67, 73, 67, 70)
```
```{r}
inches*2.54
```
### 2.12.2
```{r}
murder_rate <- murders$total / murders$population *100000
```

```{r}
murders$abb[order(murder_rate)]
```

## 2.12 Exercises

1.
```{r}
city_temps <- data.frame(name = city, temperature = temp)
temp = 5/9*(temp-32)
temp
```

2.
```{r}
x <- c(1:100)
sum(1/x^2)
```
3.
```{r}
str(murders)
murder_rate <- murders$total/murders$population*100000
mean(murder_rate)
```

## 2.13 Indexing

```{r}
ind <- murder_rate <= 0.71
```

```{r}
murders$state[ind]
```
```{r}
sum(ind)
```
```{r}
west <- murders$region == "West"
safe <- murder_rate <=1
ind <- safe & west
murders$state[ind]
ind <- which(murders$state == "California")
murder_rate[ind]
murder_rate[33]
ind <- match(c("New York", "Florida", "Texas"), murders$state)
ind
murder_rate[ind]
```



The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
